import matplotlib as mpl
mpl.use('Agg')
from matplotlib import pyplot as plt
import seaborn as sns
import pickle
import os
import gzip
import argparse
import numpy as np
import re
import statistics
from collections import namedtuple
from collections import defaultdict
import sys
import pysam
import pandas as pd
sys.path.append('HapCUT2/utilities')
import calculate_haplotype_statistics
import random
from analyze_variants import count_fp_near_true_indel
from matplotlib_venn import venn3
import matplotlib.gridspec as gridspec

mpl.rc('legend', fontsize=9)
mpl.rc('xtick', labelsize=9)
mpl.rc('ytick', labelsize=9)
mpl.rc('axes', labelsize=9)
mpl.rc('axes', labelsize=9)
mpl.rcParams.update({'font.size': 9})
mpl.rc('lines', linewidth=1.5)
mpl.rc('mathtext',default='regular')

def parseargs():

    parser = argparse.ArgumentParser(description='this tool is meant to make precision-recall curves from RTGtools vcfeval data, that are prettier than those from RTGtools rocplot function.')
    parser.add_argument('-i', '--input_dirs', nargs='+', type = str, help='list of directories generated by RTGtools vcfeval tool', default=None)
    parser.add_argument('-l', '--labels', nargs='+', type = str, help='list of labels to associate to input_dirs', default=None)
    parser.add_argument('-o', '--output_file', nargs='?', type = str, help='PNG file to write plot to.', default=None)
    parser.add_argument('-t', '--title', nargs='?', type = str, help='title for plot', default=None)

    args = parser.parse_args()
    return args

def format_bp(basepairs):
    if basepairs / 1e9 > 1.0:
        return "{:.1f} Gb".format(basepairs / 1e9)
    elif basepairs / 1e6 > 1.0:
        return "{:.1f} Mb".format(basepairs / 1e6)
    elif basepairs / 1e3 > 1.0:
        return "{:.1f} kb".format(basepairs / 1e3)
    else:
        return "{} bp".format(int(basepairs))

def plot_vcfeval(dirlist, labels, output_file, title, colors=['r','#3333ff','#ccccff','#9999ff','#8080ff','#6666ff'], xlim=(0.6,1.0), ylim=(0.95,1.0), legendloc='lower left'):


    # add a small amount of padding to the xlim and ylim so that grid lines show up on the borders
    xpad = (xlim[1] - xlim[0])/100
    ypad = (ylim[1] - ylim[0])/100
    xlim = (xlim[0]-xpad, xlim[1]+xpad)
    ylim = (ylim[0]-ypad, ylim[1]+ypad)

    plt.figure();
    ax1 = plt.subplot(111)
    if title != None:
        plt.title(title)

    if len(dirlist) > len(colors):
        print("need to define larger color pallet to plot this many datasets.")
        exit(1)

    for color, path, label in zip(colors, dirlist,labels):

        #quals = []
        recalls = []
        precisions = []

        with gzip.open(os.path.join(path,'snp_roc.tsv.gz'),mode='rt') as inf:

            for line in inf:
                if line[0] == '#':
                    continue
                else:
                    el = [float(x) for x in line.strip().split()]
                    assert(len(el) == 8)
                    #quals.append(el[0])
                    precisions.append(el[5])
                    recalls.append(el[6])

        plt.plot(recalls, precisions, color=color,label=label,linewidth=3,alpha=0.75)

    plt.grid(True,color='grey',linestyle='--',alpha=0.5)

    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)
    ax1.spines["bottom"].set_visible(False)
    ax1.spines["left"].set_visible(False)
    plt.tick_params(axis="both", which="both", bottom="off", top="off",
                labelbottom="on", left="off", right="off", labelleft="on")

    plt.xlim(xlim)
    plt.ylim(ylim)
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.legend(loc=legendloc)
    plt.tight_layout()
    ax1.set_axisbelow(True)
    plt.savefig(output_file, dpi = 600)

def plot_vcfeval_4panel(dirlist1, labels1, colors1, legendloc1, title1,
                        dirlist2, labels2, colors2, legendloc2, title2,
                        dirlist3, labels3, colors3, legendloc3, title3,
                        dirlist4, labels4, colors4, legendloc4, title4,
                        xlim, ylim,
                        output_file):

    xpad = (xlim[1] - xlim[0])/100
    ypad = (ylim[1] - ylim[0])/100
    xlim = (xlim[0]-xpad, xlim[1]+xpad)
    ylim = (ylim[0]-ypad, ylim[1]+ypad)

    def plot_panel(ax, dirlist, labels, colors, legendloc, xlim, ylim, labelbottom, labelleft, title, letter_label):
        # add a small amount of padding to the xlim and ylim so that grid lines show up on the borders

        if len(dirlist) > len(colors):
            print("need to define larger color pallet to plot this many datasets.")
            exit(1)

        for color, path, label in zip(colors, dirlist,labels):

            #quals = []
            recalls = []
            precisions = []

            with gzip.open(os.path.join(path,'snp_roc.tsv.gz'),mode='rt') as inf:

                for line in inf:
                    if line[0] == '#':
                        continue
                    else:
                        el = [float(x) for x in line.strip().split()]
                        assert(len(el) == 8)
                        #quals.append(el[0])
                        precisions.append(el[5])
                        recalls.append(el[6])

            ax.plot(recalls, precisions, color=color,label=label,linewidth=1.5,alpha=0.75)

        ax.grid(True,color='grey',linestyle='--',alpha=0.5)

        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["bottom"].set_visible(False)
        ax.spines["left"].set_visible(False)
        ax.tick_params(axis="both", which="both", bottom="off", top="off",
                    labelbottom=labelbottom, left="off", right="off", labelleft=labelleft)

        ax.set_xlim(xlim)
        ax.set_ylim(ylim)
        ax.text(-0.05, 1.07, letter_label, transform=ax.transAxes,fontsize=11, fontweight='bold', va='top')

        #plt.xlabel('Recall')
        #plt.ylabel('Precision')
        ax.legend(loc=legendloc,title=title)
        #plt.tight_layout()
        ax.set_axisbelow(True)

    fig = plt.figure(figsize=(7, 6))
    gs1 = gridspec.GridSpec(2, 2)
    gs1.update(wspace=0.1, hspace=0.1) # set the spacing between axes.

    ax1 = plt.subplot(gs1[0])
    plot_panel(ax=ax1,dirlist=dirlist1, labels=labels1, colors=colors1, legendloc=legendloc1, xlim=xlim, ylim=ylim, title=title1, labelbottom='off', labelleft='on', letter_label='a')

    ax2 = plt.subplot(gs1[1])
    plot_panel(ax=ax2,dirlist=dirlist2, labels=labels2, colors=colors2, legendloc=legendloc2, xlim=xlim, ylim=ylim, title=title2, labelbottom='off', labelleft='off', letter_label='b')

    ax3 = plt.subplot(gs1[2])
    plot_panel(ax=ax3,dirlist=dirlist3, labels=labels3, colors=colors3, legendloc=legendloc3, xlim=xlim, ylim=ylim, title=title3, labelbottom='on', labelleft='on', letter_label='c')

    ax4 = plt.subplot(gs1[3])
    plot_panel(ax=ax4,dirlist=dirlist4, labels=labels4, colors=colors4, legendloc=legendloc4, xlim=xlim, ylim=ylim, title=title4, labelbottom='on', labelleft='off', letter_label='d')

    fig.text(0.5, 0.03, 'Recall', ha='center')
    fig.text(0.02, 0.5, 'Precision', va='center', rotation='vertical')

    plt.savefig(output_file, dpi = 600)

# input:
# vcfeval_dir: directory containing vcfeval output
# gq_cutoff: a Genotype Quality value to set as the cutoff for variants e.g. 30 or 50
# output:
# (precision, recall) : the precision and recall values for variants above the GQ cutoff
def get_precision_recall(vcfeval_dir, gq_cutoff):

    recall = None
    precision = None
    qual = None

    with gzip.open(os.path.join(vcfeval_dir,'snp_roc.tsv.gz'),mode='rt') as inf:

        for line in inf:
            if line[0] == '#':
                continue
            else:
                el = [float(x) for x in line.strip().split()]
                assert(len(el) == 8)
                new_qual = el[0]
                if new_qual < gq_cutoff:
                    break

                qual = new_qual
                precision = el[5]
                recall = el[6]

    # this should be true for large enough datasets, like we will look at,
    # and it's a nice sanity check
    assert(qual - gq_cutoff >= 0)
    assert(qual - gq_cutoff < 1.0)
    assert(precision != None)
    assert(recall != None)

    return (precision, recall)

def plot_precision_recall_bars_simulation(pacbio_dirlist_genome, illumina_dirlist_genome, pacbio_dirlist_segdup, illumina_dirlist_segdup, gq_cutoff, labels, output_file):

    plt.figure(figsize=(7,5))
    #mpl.rcParams['axes.titlepad'] = 50

    width = 0.15
    alpha1 = 0.6

    # credit for this function: http://composition.al/blog/2015/11/29/a-better-way-to-add-labels-to-bar-charts-with-matplotlib/
    def autolabel(rects, ax, format_str="{0:.4f}"):
        # Get y-axis height to calculate label position from.
        (y_bottom, y_top) = ax.get_ylim()
        y_height = y_top - y_bottom

        for rect in rects:
            height = rect.get_height()

            # Fraction of axis height taken up by this rectangle
            p_height = (height / y_height)

            label_position = height + (y_height * 0.01)

            ax.text(rect.get_x() + rect.get_width()/2., label_position,
                    format_str.format(height),
                    ha='center', va='bottom', fontsize=3.5)

    def make_subplot(ax, ind, pacbio_vals, illumina_vals, lab_pacbio=None, lab_illumina=None, fc='#ffffff'):

        rects1 = plt.bar(ind+width, pacbio_vals, color='#2200ff',
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_pacbio,
                zorder=0)
        autolabel(rects1, ax)
        rects2 = plt.bar(ind+2*width, illumina_vals, color='#ff1900',
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_illumina,
                zorder=0)
        autolabel(rects2, ax)

        # add some text for labels, title and axes ticks
        #plt.xlim(-0.5,6)

    def prettify_plot():

        ax.yaxis.grid(True,color='grey', alpha=0.5, linestyle='--',zorder=1.0)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["bottom"].set_visible(False)
        ax.spines["left"].set_visible(False)
        plt.tick_params(axis="both", which="both", bottom=False, top=False,
                    labelbottom=True, left=False, right=False, labelleft=True)


    ind1 = [0,0.5,1,1.5]
    ind2 = [2.25,2.75,3.25,3.75]
    ind = ind1 + ind2

    pacbio_precisions_genome, pacbio_recalls_genome = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_dirlist_genome])
    illumina_precisions_genome, illumina_recalls_genome = zip(*[get_precision_recall(d, gq_cutoff) for d in illumina_dirlist_genome])
    pacbio_precisions_segdup, pacbio_recalls_segdup = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_dirlist_segdup])
    illumina_precisions_segdup, illumina_recalls_segdup = zip(*[get_precision_recall(d, gq_cutoff) for d in illumina_dirlist_segdup])

    ax = plt.subplot(211)
    plt.ylim(0.99,1.0)
    make_subplot(ax,np.array(ind1), pacbio_precisions_genome, illumina_precisions_genome, lab_pacbio='PacBio + BLASR + Longshot', lab_illumina='Illumina + BWA-MEM + Freebayes',fc='#e0e1e2')
    make_subplot(ax, np.array(ind2), pacbio_precisions_segdup, illumina_precisions_segdup,fc='#dddddd')
    ax.legend(loc='center left', bbox_to_anchor=(0.05,1.13),ncol=2)

    plt.ylabel("Precision")
    prettify_plot()
    ax.set_xticks([])
    ax.set_xticklabels([])

    ax = plt.subplot(212)
    plt.ylabel("Recall\n")
    plt.ylim(0.0-0.001,1.001)
    make_subplot(ax, np.array(ind1), pacbio_recalls_genome, illumina_recalls_genome,fc='#e0e1e2')
    make_subplot(ax, np.array(ind2), pacbio_recalls_segdup, illumina_recalls_segdup,fc='#dddddd')
    prettify_plot()
    ax.set_xticks(np.array(ind)+1.5*width)
    ax.set_xticklabels(labels+labels)

    #ax.set_yscale('log')NA12878_prec_recall_{chrom}
    #plt.xlim(())
    #plt.ylim((0,1.0))
    #plt.legend(loc='upper left')
    plt.xlabel(" ",labelpad=10)

    plt.tight_layout()
    plt.subplots_adjust(top=0.90)
    #t = plt.suptitle(title)

    ax.set_axisbelow(True)

    ticklabelpad = mpl.rcParams['xtick.major.pad']

    ax.annotate('coverage', xy=(-0.1,-0.03), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax.annotate('Whole Genome', xy=(0.16,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax.annotate('Segmental Duplications Only', xy=(0.58,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')

    # credit to https://stackoverflow.com/questions/4700614/how-to-put-the-legend-out-of-the-plot
    # Shrink current axis by 20%
    box = ax.get_position()
    #ax.set_position([box.x0, box.y0, box.width * 0.85, box.height])
    # Put a legend to the right of the current axis
    #ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))

    #plt.show()
    plt.savefig(output_file, dpi = 600)

def plot_precision_recall_bars_simulation_extended(pacbio_ngmlr_dirlist_genome,
                                                      pacbio_minimap2_dirlist_genome,
                                                      pacbio_bwamem_dirlist_genome,
                                                      pacbio_blasr_dirlist_genome,
                                                      illumina_dirlist_genome,
                                                      pacbio_ngmlr_dirlist_segdup,
                                                      pacbio_minimap2_dirlist_segdup,
                                                      pacbio_bwamem_dirlist_segdup,
                                                      pacbio_blasr_dirlist_segdup,
                                                      illumina_dirlist_segdup,
                                                      gq_cutoff, labels, output_file):

    plt.figure(figsize=(7,5))
    #mpl.rcParams['axes.titlepad'] = 50

    width = 0.075
    alpha1 = 0.6

    def make_subplot(ax,
                     ind,
                     pacbio_ngmlr_vals,
                     pacbio_minimap2_vals,
                     pacbio_bwamem_vals,
                     pacbio_blasr_vals,
                     illumina_vals,
                     lab_pacbio_ngmlr=None,
                     lab_pacbio_minimap2=None,
                     lab_pacbio_bwamem=None,
                     lab_pacbio_blasr=None,
                     lab_illumina=None):

        plt.bar(ind+width, pacbio_ngmlr_vals, color='#ffe500',
                ecolor='black',
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_pacbio_ngmlr,
                zorder=0)
        plt.bar(ind+2*width, pacbio_minimap2_vals, color='#00ff33',
                ecolor='black',
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_pacbio_minimap2,
                zorder=0)
        plt.bar(ind+3*width, pacbio_bwamem_vals, color='#ff0094',
                ecolor='black',
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_pacbio_bwamem,
                zorder=0)
        plt.bar(ind+4*width, pacbio_blasr_vals, color='#2200ff',
                ecolor='black',
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_pacbio_blasr,
                zorder=0)
        plt.bar(ind+5*width, illumina_vals, color='#ff1900',
                ecolor='black',
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_illumina,
                zorder=0)
        # add some text for labels, title and axes ticks
        #plt.xlim(-0.5,6)


    def prettify_plot(ax):

        ax.yaxis.grid(True,color='grey', linestyle='--', alpha=0.5, zorder=1.0)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["bottom"].set_visible(False)
        ax.spines["left"].set_visible(False)
        plt.tick_params(axis="both", which="both", bottom=False, top=False,
                    labelbottom=True, left=False, right=False, labelleft=True)


    ind1 = [0,0.5,1,1.5]
    ind2 = [2.25,2.75,3.25,3.75]
    ind = ind1 + ind2

    pacbio_ngmlr_precisions_genome, pacbio_ngmlr_recalls_genome = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_ngmlr_dirlist_genome])
    pacbio_minimap2_precisions_genome, pacbio_minimap2_recalls_genome = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_minimap2_dirlist_genome])
    pacbio_bwamem_precisions_genome, pacbio_bwamem_recalls_genome = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_bwamem_dirlist_genome])
    pacbio_blasr_precisions_genome, pacbio_blasr_recalls_genome = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_blasr_dirlist_genome])
    illumina_precisions_genome, illumina_recalls_genome = zip(*[get_precision_recall(d, gq_cutoff) for d in illumina_dirlist_genome])

    pacbio_ngmlr_precisions_segdup, pacbio_ngmlr_recalls_segdup = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_ngmlr_dirlist_segdup])
    pacbio_minimap2_precisions_segdup, pacbio_minimap2_recalls_segdup = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_minimap2_dirlist_segdup])
    pacbio_bwamem_precisions_segdup, pacbio_bwamem_recalls_segdup = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_bwamem_dirlist_segdup])
    pacbio_blasr_precisions_segdup, pacbio_blasr_recalls_segdup = zip(*[get_precision_recall(d, gq_cutoff) for d in pacbio_blasr_dirlist_segdup])
    illumina_precisions_segdup, illumina_recalls_segdup = zip(*[get_precision_recall(d, gq_cutoff) for d in illumina_dirlist_segdup])

    ax1 = plt.subplot(211)
    make_subplot(ax=ax1,
                ind=np.array(ind1),
                pacbio_ngmlr_vals=pacbio_ngmlr_precisions_genome,
                pacbio_minimap2_vals=pacbio_minimap2_precisions_genome,
                pacbio_bwamem_vals=pacbio_bwamem_precisions_genome,
                pacbio_blasr_vals=pacbio_blasr_precisions_genome,
                illumina_vals=illumina_precisions_genome,
                lab_pacbio_ngmlr='PacBio + NGMLR + Longshot',
                lab_pacbio_minimap2='PacBio + Minimap2 + Longshot',
                lab_pacbio_bwamem='PacBio + BWA-MEM + Longshot',
                lab_pacbio_blasr='PacBio + BLASR + Longshot',
                lab_illumina='Illumina + BWA-MEM + Freebayes')

    make_subplot(ax=ax1,
                ind=np.array(ind2),
                pacbio_ngmlr_vals=pacbio_ngmlr_precisions_segdup,
                pacbio_minimap2_vals=pacbio_minimap2_precisions_segdup,
                pacbio_bwamem_vals=pacbio_bwamem_precisions_segdup,
                pacbio_blasr_vals=pacbio_blasr_precisions_segdup,
                illumina_vals=illumina_precisions_segdup)

    ax1.legend(loc='center left', bbox_to_anchor=(0.1,1.25),ncol=2)

    plt.ylabel("Precision")
    plt.ylim(0.9,1.0)
    ax1.set_xticks([])
    ax1.set_xticklabels([])

    prettify_plot(ax1)
    ax2 = plt.subplot(212)
    plt.ylabel("Recall\n")
    plt.ylim(0.0-0.001,1.001)

    make_subplot(ax=ax2,
                ind=np.array(ind1),
                pacbio_ngmlr_vals=pacbio_ngmlr_recalls_genome,
                pacbio_minimap2_vals=pacbio_minimap2_recalls_genome,
                pacbio_bwamem_vals=pacbio_bwamem_recalls_genome,
                pacbio_blasr_vals=pacbio_blasr_recalls_genome,
                illumina_vals=illumina_recalls_genome)

    make_subplot(ax=ax2,
                ind=np.array(ind2),
                pacbio_ngmlr_vals=pacbio_ngmlr_recalls_segdup,
                pacbio_minimap2_vals=pacbio_minimap2_recalls_segdup,
                pacbio_bwamem_vals=pacbio_bwamem_recalls_segdup,
                pacbio_blasr_vals=pacbio_blasr_recalls_segdup,
                illumina_vals=illumina_recalls_segdup)

    ax2.set_xticks(np.array(ind)+3*width)
    ax2.set_xticklabels(labels+labels)

    #ax.set_yscale('log')NA12878_prec_recall_{chrom}
    #plt.xlim(())
    #plt.ylim((0,1.0))
    #plt.legend(loc='upper left')
    plt.xlabel(" ",labelpad=10)

    plt.tight_layout()
    plt.subplots_adjust(top=0.82)
    #t = plt.suptitle(title)

    ax2.set_axisbelow(True)

    ticklabelpad = mpl.rcParams['xtick.major.pad']

    ax2.annotate('coverage', xy=(-0.1,-0.03), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax2.annotate('Whole Genome', xy=(0.16,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax2.annotate('Segmental Duplications Only', xy=(0.58,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    prettify_plot(ax2)

    # credit to https://stackoverflow.com/questions/4700614/how-to-put-the-legend-out-of-the-plot
    # Shrink current axis by 20%
    #box = ax2.get_position()
    #ax.set_position([box.x0, box.y0, box.width * 0.85, box.height])
    # Put a legend to the right of the current axis
    #ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))

    #plt.show()
    plt.savefig(output_file, dpi = 600)


def plot_precision_recall_bars_NA12878_AJ_Trio_with_haplotyping_results(pacbio_dirlist_NA12878, illumina_dirlist_NA12878,
                                               pacbio_dirlist_NA24385, illumina_dirlist_NA24385,
                                               pacbio_dirlist_NA24149, illumina_dirlist_NA24149,
                                               pacbio_dirlist_NA24143, illumina_dirlist_NA24143,
                                               gq_cutoffs_NA12878, gq_cutoffs_NA24385,
                                               gq_cutoffs_NA24149, gq_cutoffs_NA24143,
                                               gq_cutoff_illumina, labels_variants, labels_hap, longshot_errs, illumina_errs,
                                               output_file):

    fig = plt.figure(constrained_layout=True, figsize=(9,7))
    gs = gridspec.GridSpec(ncols=4, nrows=13, figure=fig)

    width = 0.09
    alpha1 = 0.6

    # credit for this function: http://composition.al/blog/2015/11/29/a-better-way-to-add-labels-to-bar-charts-with-matplotlib/
    def autolabel(rects, ax, height_fmt_string):
        # Get y-axis height to calculate label position from.
        (y_bottom, y_top) = ax.get_ylim()
        y_height = y_top - y_bottom

        for rect in rects:
            height = rect.get_height()

            # Fraction of axis height taken up by this rectangle
            p_height = (height / y_height)

            label_position = height + (y_height * 0.01)

            ax.text(rect.get_x() + rect.get_width()/2., label_position,
                    height_fmt_string.format(height),
                    ha='center', va='bottom', fontsize=6)

    def plot_bars(ax, ind, vals, color=None, lab=None, height_fmt_string="{0:.4f}", letter_label=None):

        rects = plt.bar(ind+width, vals, color=color,
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab,
                zorder=0)

        autolabel(rects, ax, height_fmt_string)


    def prettify_plot(ax):
        ax.set_facecolor('#f7f7f7')
        ax.yaxis.grid(True,color='grey', alpha=0.5, linestyle='--',zorder=1.0)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["bottom"].set_visible(False)
        ax.spines["left"].set_visible(False)
        plt.tick_params(axis="both", which="both", bottom=False, top=False,
                    labelbottom=True, left=False, right=False, labelleft=True)

    ind_NA12878_pacbio = [0,0.1]
    ind_NA12878_illumina = [0.2]
    ind_NA24385_pacbio = [0.4,0.5,0.6,0.7]
    ind_NA24385_illumina = [0.8]
    ind_NA24149_pacbio = [1.0]
    ind_NA24149_illumina = [1.1]
    ind_NA24143_pacbio = [1.3]
    ind_NA24143_illumina = [1.4]

    pacbio_precisions_NA24385, pacbio_recalls_NA24385 = zip(*[get_precision_recall(d, g) for d,g in zip(pacbio_dirlist_NA24385, gq_cutoffs_NA24385)])
    illumina_precisions_NA24385, illumina_recalls_NA24385 = zip(*[get_precision_recall(d, gq_cutoff_illumina) for d in illumina_dirlist_NA24385])
    pacbio_precisions_NA24149, pacbio_recalls_NA24149 = zip(*[get_precision_recall(d, g) for d,g in zip(pacbio_dirlist_NA24149, gq_cutoffs_NA24149)])
    illumina_precisions_NA24149, illumina_recalls_NA24149 = zip(*[get_precision_recall(d, gq_cutoff_illumina) for d in illumina_dirlist_NA24149])
    pacbio_precisions_NA24143, pacbio_recalls_NA24143 = zip(*[get_precision_recall(d, g) for d,g in zip(pacbio_dirlist_NA24143, gq_cutoffs_NA24143)])
    illumina_precisions_NA24143, illumina_recalls_NA24143 = zip(*[get_precision_recall(d, gq_cutoff_illumina) for d in illumina_dirlist_NA24143])
    pacbio_precisions_NA12878, pacbio_recalls_NA12878 = zip(*[get_precision_recall(d, g) for d,g in zip(pacbio_dirlist_NA12878, gq_cutoffs_NA12878)])
    illumina_precisions_NA12878, illumina_recalls_NA12878 = zip(*[get_precision_recall(d, gq_cutoff_illumina) for d in illumina_dirlist_NA12878])

    ax1 = fig.add_subplot(gs[1:7,0:3])
    plt.ylim(0.95,1.0)

    plot_bars(ax1, np.array(ind_NA12878_pacbio), pacbio_precisions_NA12878,color='#2200ff',lab='Longshot (PacBio)')
    plot_bars(ax1, np.array(ind_NA12878_illumina), illumina_precisions_NA12878,color='#ff1900',lab='Freebayes (Illumina)')
    plot_bars(ax1, np.array(ind_NA24385_pacbio), pacbio_precisions_NA24385,color='#2200ff')
    plot_bars(ax1, np.array(ind_NA24385_illumina), illumina_precisions_NA24385,color='#ff1900')
    plot_bars(ax1, np.array(ind_NA24149_pacbio), pacbio_precisions_NA24149,color='#2200ff')
    plot_bars(ax1, np.array(ind_NA24149_illumina), illumina_precisions_NA24149,color='#ff1900')
    plot_bars(ax1, np.array(ind_NA24143_pacbio), pacbio_precisions_NA24143,color='#2200ff')
    plot_bars(ax1, np.array(ind_NA24143_illumina), illumina_precisions_NA24143,color='#ff1900')
    ax1.legend(loc='center left', bbox_to_anchor=(0.3,1.12),ncol=2)
    ax1.text(-0.01, 1.055, 'a', transform=ax1.transAxes,fontsize=11, fontweight='bold', va='top')

    plt.ylabel("SNV Precision")
    #plt.ylim(0,1.0)
    prettify_plot(ax1)
    ax1.set_xticks([])
    ax1.set_xticklabels([])

    ax2 = fig.add_subplot(gs[7:13,0:3])
    plt.ylabel("SNV Recall")
    plot_bars(ax2, np.array(ind_NA12878_pacbio), pacbio_recalls_NA12878,color='#2200ff')
    plot_bars(ax2, np.array(ind_NA12878_illumina), illumina_recalls_NA12878,color='#ff1900')
    plot_bars(ax2, np.array(ind_NA24385_pacbio), pacbio_recalls_NA24385,color='#2200ff')
    plot_bars(ax2, np.array(ind_NA24385_illumina), illumina_recalls_NA24385,color='#ff1900')
    plot_bars(ax2, np.array(ind_NA24149_pacbio), pacbio_recalls_NA24149,color='#2200ff')
    plot_bars(ax2, np.array(ind_NA24149_illumina), illumina_recalls_NA24149,color='#ff1900')
    plot_bars(ax2, np.array(ind_NA24143_pacbio), pacbio_recalls_NA24143,color='#2200ff')
    plot_bars(ax2, np.array(ind_NA24143_illumina), illumina_recalls_NA24143,color='#ff1900')
    prettify_plot(ax2)
    ax2.set_xticks(np.array(ind_NA12878_pacbio+ind_NA12878_illumina
                          +ind_NA24385_pacbio+ind_NA24385_illumina
                          +ind_NA24149_pacbio+ind_NA24149_illumina
                          +ind_NA24143_pacbio+ind_NA24143_illumina)+1.0*width)
    ax2.set_xticklabels(labels_variants)
    ax2.text(-0.01, 1.055, 'b', transform=ax2.transAxes,fontsize=11, fontweight='bold', va='top')

    #ax.set_yscale('log')NA12878_prec_recall_{chrom}
    #plt.xlim(())
    #plt.ylim((0,1.0))
    #plt.legend(loc='upper left')
    plt.xlabel(" ",labelpad=10)

    #plt.tight_layout()
    #plt.subplots_adjust(top=0.85)
    #t = plt.suptitle(title)

    ax2.set_axisbelow(True)

    ticklabelpad = mpl.rcParams['xtick.major.pad']

    ax2.annotate('coverage', xy=(-0.1,-0.03), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax2.annotate('NA12878', xy=(0.07,-0.1), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax2.annotate('NA24385', xy=(0.38,-0.1), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax2.annotate('NA24149', xy=(0.66,-0.1), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax2.annotate('NA24143', xy=(0.84,-0.1), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')

    ###############################################################################
    # plot haplotyping results
    ###############################################################################

    #mpl.rcParams['axes.titlepad'] = 50

    width = 0.09
    alpha1 = 0.6

    def make_hap_subplot(ax, ind, longshot_vals, illumina_vals):

        plt.bar(ind+width, longshot_vals, color='#2200ff',
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                zorder=0)
        plt.bar(ind+2.1*width, illumina_vals, color='#ff1900',
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                zorder=0)
        # add some text for labels, title and axes ticks
        #plt.xlim(-0.5,6)

    #unpickle the error objects
    longshot_errs = [pickle.load(open(f,'rb')) for f in longshot_errs]
    illumina_errs = [pickle.load(open(f,'rb')) for f in illumina_errs]

    ind = [0,0.1,0.3,0.4]
    #ind_NA24149_pacbio = [1.0]
    #ind_NA24149_illumina = [1.1]
    #ind_NA24143_pacbio = [1.3]
    #ind_NA24143_illumina = [1.4]

    ax3 = fig.add_subplot(gs[1:5,3])
    longshot_switch_mismatch = [e.get_switch_mismatch_rate() for e in longshot_errs]
    illumina_switch_mismatch = [e.get_switch_mismatch_rate() for e in illumina_errs]
    plot_bars(ax3, ind[0], longshot_switch_mismatch[0], color='#2200ff')
    plot_bars(ax3, ind[1], illumina_switch_mismatch[0], color='#ff1900')
    plot_bars(ax3, ind[2], longshot_switch_mismatch[1], color='#2200ff')
    plot_bars(ax3, ind[3], illumina_switch_mismatch[1], color='#ff1900')

    plt.ylabel("Haplotype Combined\nSwitch Error Rate")

    prettify_plot(ax3)
    ax3.set_xticks([])
    ax3.set_xticklabels([])
    ax3.text(-0.05, 1.07, 'c', transform=ax3.transAxes,fontsize=11, fontweight='bold', va='top')

    ax4 = fig.add_subplot(gs[5:9,3])
    longshot_median_len = [e.get_N50_phased_portion()/1000 for e in longshot_errs]
    illumina_median_len = [e.get_N50_phased_portion()/1000 for e in illumina_errs]
    #make_hap_subplot(ax4,np.array(ind), longshot_median_len, illumina_median_len)
    plot_bars(ax4, ind[0], longshot_median_len[0], color='#2200ff', height_fmt_string="{0:.1f}")
    plot_bars(ax4, ind[1], illumina_median_len[0], color='#ff1900', height_fmt_string="{0:.1f}")
    plot_bars(ax4, ind[2], longshot_median_len[1], color='#2200ff', height_fmt_string="{0:.1f}")
    plot_bars(ax4, ind[3], illumina_median_len[1], color='#ff1900', height_fmt_string="{0:.1f}")
    plt.ylabel("Haplotype N50 (kb)")
    prettify_plot(ax4)
    ax4.set_xticks([])
    ax4.set_xticklabels([])
    ax4.text(-0.05, 1.07, 'd', transform=ax4.transAxes,fontsize=11, fontweight='bold', va='top')


    ax5 = fig.add_subplot(gs[9:13,3])
    longshot_fraction_phased = [e.get_phased_count() / e.get_num_snps() for e in longshot_errs]
    illumina_fraction_phased = [e.get_phased_count() / e.get_num_snps() for e in illumina_errs]
    plot_bars(ax5, ind[0], longshot_fraction_phased[0], color='#2200ff')
    plot_bars(ax5, ind[1], illumina_fraction_phased[0], color='#ff1900')
    plot_bars(ax5, ind[2], longshot_fraction_phased[1], color='#2200ff')
    plot_bars(ax5, ind[3], illumina_fraction_phased[1], color='#ff1900')

    #make_hap_subplot(ax5,np.array(ind), longshot_fraction_phased, illumina_fraction_phased)
    plt.ylabel("Fraction of Heterozygous\nVariants Phased")
    prettify_plot(ax5)
    ax5.set_xticks(np.array(ind)+width)
    ax5.set_xticklabels(labels_hap)
    ax5.tick_params(pad=1)

    ax5.annotate('NA12878', xy=(0.01,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax5.annotate('NA24385', xy=(0.55,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax5.text(-0.05, 1.07, 'e', transform=ax5.transAxes,fontsize=11, fontweight='bold', va='top')

    plt.xlabel(" ",labelpad=10)

    #plt.tight_layout()
    #plt.subplots_adjust(top=0.90)

    ax5.set_axisbelow(True)

    ticklabelpad = mpl.rcParams['xtick.major.pad']

    plt.savefig(output_file, dpi=600)


def plot_haplotyping_results(longshot_errs, hapcut2_errs, median_covs, output_file):
    # errs should be in order: NA12878 44x, NA24385 69x
    assert(len(longshot_errs) == 2)
    assert(len(hapcut2_errs) == 2)
    assert(len(median_covs) == 2)

    #unpickle the error objects
    longshot_errs = [pickle.load(open(f,'rb')) for f in longshot_errs]
    hapcut2_errs = [pickle.load(open(f,'rb')) for f in hapcut2_errs]

    plt.figure(figsize=(5,6))
    #mpl.rcParams['axes.titlepad'] = 50

    width = 0.10
    alpha1 = 0.6

    # credit for this function: http://composition.al/blog/2015/11/29/a-better-way-to-add-labels-to-bar-charts-with-matplotlib/
    def autolabel(rects, ax, format_str="{0:.4f}"):
        # Get y-axis height to calculate label position from.
        (y_bottom, y_top) = ax.get_ylim()
        y_height = y_top - y_bottom

        for rect in rects:
            height = rect.get_height()

            # Fraction of axis height taken up by this rectangle
            p_height = (height / y_height)

            label_position = height + (y_height * 0.01)

            ax.text(rect.get_x() + rect.get_width()/2., label_position,
                    format_str.format(height),
                    ha='center', va='bottom', fontsize=6)

    def make_subplot(ax, ind, longshot_vals, hapcut2_vals, lab_longshot=None, lab_hapcut2=None, letter_label=None, format_str="{0:.4f}"):

        rects1 = plt.bar(ind+width, longshot_vals, color='#2200ff',
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_longshot,
                zorder=0)
        autolabel(rects1, ax, format_str)

        rects2 = plt.bar(ind+2*width, hapcut2_vals, color='k',
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab_hapcut2,
                zorder=0)

        autolabel(rects2, ax, format_str)
        #ax.text(-0.05, 1.07, letter_label, transform=ax.transAxes,fontsize=11, fontweight='bold', va='top')

        # add some text for labels, title and axes ticks
        #plt.xlim(-0.5,6)


    def prettify_plot():

        ax.yaxis.grid(True,color='grey', alpha=0.5, linestyle='--',zorder=1.0)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["bottom"].set_visible(False)
        ax.spines["left"].set_visible(False)
        plt.tick_params(axis="both", which="both", bottom=False, top=False,
                    labelbottom=True, left=False, right=False, labelleft=True)


    ind = [0,0.3]

    ax = plt.subplot(211)
    longshot_switch_mismatch = [e.get_switch_mismatch_rate() for e in longshot_errs]
    hapcut2_switch_mismatch = [e.get_switch_mismatch_rate() for e in hapcut2_errs]
    make_subplot(ax,np.array(ind), longshot_switch_mismatch, hapcut2_switch_mismatch, lab_longshot='Longshot Haplotype', lab_hapcut2='~30' + r'$\times$' + ' Illumina + HapCUT2 Haplotype', letter_label='a')
    ax.legend(loc='center left', bbox_to_anchor=(0.0,1.15),ncol=1)

    plt.ylabel("Switch + Mismatch Error Rate")
    #plt.ylim(0.99,1.0)
    prettify_plot()
    ax.set_xticks([])
    ax.set_xticklabels([])

    ax = plt.subplot(212)
    plt.ylabel("N50 (kb)")
    longshot_N50 = [e.get_N50_phased_portion()/1000 for e in longshot_errs]
    hapcut2_N50 = [e.get_N50_phased_portion()/1000  for e in hapcut2_errs]
    make_subplot(ax,np.array(ind), longshot_N50, hapcut2_N50, letter_label='b', format_str='{0:.1f}')
    prettify_plot()
    ax.set_xticks(np.array(ind)+1.5*width)
    ax.set_xticklabels(['NA12878\n{}'.format(median_covs[0]) + r'$\times$','NA24385\n{}'.format(median_covs[1]) + r'$\times$'])

    #ax.set_yscale('log')NA12878_prec_recall_{chrom}
    #plt.xlim(())
    #plt.ylim((0,1.0))
    #plt.legend(loc='upper left')
    plt.xlabel(" ",labelpad=10)

    plt.tight_layout()
    plt.subplots_adjust(top=0.90)
    #t = plt.suptitle(title)

    ax.set_axisbelow(True)

    ticklabelpad = mpl.rcParams['xtick.major.pad']

    # credit to https://stackoverflow.com/questions/4700614/how-to-put-the-legend-out-of-the-plot
    # Shrink current axis by 20%
    box = ax.get_position()
    #ax.set_position([box.x0, box.y0, box.width * 0.85, box.height])
    # Put a legend to the right of the current axis
    #ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))

    #plt.show()
    plt.savefig(output_file, dpi = 600)

def plot_precision_recall_bars_NA12878_AJ_Trio(pacbio_dirlist_NA12878, illumina_dirlist_NA12878,
                                               pacbio_dirlist_NA24385, illumina_dirlist_NA24385,
                                               pacbio_dirlist_NA24149, illumina_dirlist_NA24149,
                                               pacbio_dirlist_NA24143, illumina_dirlist_NA24143,
                                               gq_cutoffs_NA12878, gq_cutoffs_NA24385,
                                               gq_cutoffs_NA24149, gq_cutoffs_NA24143,
                                               gq_cutoff_illumina, labels,
                                               output_file):

    plt.figure(figsize=(7,5))

    width = 0.09
    alpha1 = 0.6

    # credit for this function: http://composition.al/blog/2015/11/29/a-better-way-to-add-labels-to-bar-charts-with-matplotlib/
    def autolabel(rects, ax):
        # Get y-axis height to calculate label position from.
        (y_bottom, y_top) = ax.get_ylim()
        y_height = y_top - y_bottom

        for rect in rects:
            height = rect.get_height()

            # Fraction of axis height taken up by this rectangle
            p_height = (height / y_height)

            label_position = height + (y_height * 0.01)

            ax.text(rect.get_x() + rect.get_width()/2., label_position,
                    "{0:.4f}".format(height),
                    ha='center', va='bottom', fontsize=7)

    def plot_bars(ax, ind, vals, color=None, lab=None):

        rects = plt.bar(ind+width, vals, color=color,
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab,
                zorder=0)

        autolabel(rects, ax)


    def prettify_plot():

        ax.yaxis.grid(True,color='grey', alpha=0.5, linestyle='--',zorder=1.0)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.spines["bottom"].set_visible(False)
        ax.spines["left"].set_visible(False)
        plt.tick_params(axis="both", which="both", bottom=False, top=False,
                    labelbottom=True, left=False, right=False, labelleft=True)

    ind_NA12878_pacbio = [0,0.1]
    ind_NA12878_illumina = [0.2]
    ind_NA24385_pacbio = [0.4,0.5,0.6,0.7]
    ind_NA24385_illumina = [0.8]
    ind_NA24149_pacbio = [1.0]
    ind_NA24149_illumina = [1.1]
    ind_NA24143_pacbio = [1.3]
    ind_NA24143_illumina = [1.4]

    pacbio_precisions_NA24385, pacbio_recalls_NA24385 = zip(*[get_precision_recall(d, g) for d,g in zip(pacbio_dirlist_NA24385, gq_cutoffs_NA24385)])
    illumina_precisions_NA24385, illumina_recalls_NA24385 = zip(*[get_precision_recall(d, gq_cutoff_illumina) for d in illumina_dirlist_NA24385])
    pacbio_precisions_NA24149, pacbio_recalls_NA24149 = zip(*[get_precision_recall(d, g) for d,g in zip(pacbio_dirlist_NA24149, gq_cutoffs_NA24149)])
    illumina_precisions_NA24149, illumina_recalls_NA24149 = zip(*[get_precision_recall(d, gq_cutoff_illumina) for d in illumina_dirlist_NA24149])
    pacbio_precisions_NA24143, pacbio_recalls_NA24143 = zip(*[get_precision_recall(d, g) for d,g in zip(pacbio_dirlist_NA24143, gq_cutoffs_NA24143)])
    illumina_precisions_NA24143, illumina_recalls_NA24143 = zip(*[get_precision_recall(d, gq_cutoff_illumina) for d in illumina_dirlist_NA24143])
    pacbio_precisions_NA12878, pacbio_recalls_NA12878 = zip(*[get_precision_recall(d, g) for d,g in zip(pacbio_dirlist_NA12878, gq_cutoffs_NA12878)])
    illumina_precisions_NA12878, illumina_recalls_NA12878 = zip(*[get_precision_recall(d, gq_cutoff_illumina) for d in illumina_dirlist_NA12878])

    ax = plt.subplot(211)
    plt.ylim(0.95,1.0)

    plot_bars(ax, np.array(ind_NA12878_pacbio), pacbio_precisions_NA12878,color='#2200ff',lab='PacBio + BLASR + Longshot')
    plot_bars(ax, np.array(ind_NA12878_illumina), illumina_precisions_NA12878,color='#ff1900',lab='Illumina + BWA-MEM/NovoAlign + Freebayes')
    plot_bars(ax, np.array(ind_NA24385_pacbio), pacbio_precisions_NA24385,color='#2200ff')
    plot_bars(ax, np.array(ind_NA24385_illumina), illumina_precisions_NA24385,color='#ff1900')
    plot_bars(ax, np.array(ind_NA24149_pacbio), pacbio_precisions_NA24149,color='#2200ff')
    plot_bars(ax, np.array(ind_NA24149_illumina), illumina_precisions_NA24149,color='#ff1900')
    plot_bars(ax, np.array(ind_NA24143_pacbio), pacbio_precisions_NA24143,color='#2200ff')
    plot_bars(ax, np.array(ind_NA24143_illumina), illumina_precisions_NA24143,color='#ff1900')
    ax.legend(loc='center left', bbox_to_anchor=(0.0,1.25),ncol=2)

    plt.ylabel("Precision")
    #plt.ylim(0,1.0)
    prettify_plot()
    ax.set_xticks([])
    ax.set_xticklabels([])

    ax = plt.subplot(212)
    plt.ylabel("Recall")
    plot_bars(ax, np.array(ind_NA12878_pacbio), pacbio_recalls_NA12878,color='#2200ff')
    plot_bars(ax, np.array(ind_NA12878_illumina), illumina_recalls_NA12878,color='#ff1900')
    plot_bars(ax, np.array(ind_NA24385_pacbio), pacbio_recalls_NA24385,color='#2200ff')
    plot_bars(ax, np.array(ind_NA24385_illumina), illumina_recalls_NA24385,color='#ff1900')
    plot_bars(ax, np.array(ind_NA24149_pacbio), pacbio_recalls_NA24149,color='#2200ff')
    plot_bars(ax, np.array(ind_NA24149_illumina), illumina_recalls_NA24149,color='#ff1900')
    plot_bars(ax, np.array(ind_NA24143_pacbio), pacbio_recalls_NA24143,color='#2200ff')
    plot_bars(ax, np.array(ind_NA24143_illumina), illumina_recalls_NA24143,color='#ff1900')
    prettify_plot()
    ax.set_xticks(np.array(ind_NA12878_pacbio+ind_NA12878_illumina
                          +ind_NA24385_pacbio+ind_NA24385_illumina
                          +ind_NA24149_pacbio+ind_NA24149_illumina
                          +ind_NA24143_pacbio+ind_NA24143_illumina)+1.0*width)
    ax.set_xticklabels(labels)

    #ax.set_yscale('log')NA12878_prec_recall_{chrom}
    #plt.xlim(())
    #plt.ylim((0,1.0))
    #plt.legend(loc='upper left')
    plt.xlabel(" ",labelpad=10)

    plt.tight_layout()
    plt.subplots_adjust(top=0.85)
    #t = plt.suptitle(title)

    ax.set_axisbelow(True)

    ticklabelpad = mpl.rcParams['xtick.major.pad']

    ax.annotate('coverage', xy=(-0.1,-0.03), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax.annotate('NA12878', xy=(0.07,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax.annotate('NA24385', xy=(0.38,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax.annotate('NA24149', xy=(0.66,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')
    ax.annotate('NA24143', xy=(0.84,-0.15), xytext=(5, -ticklabelpad), ha='left', va='top',
                xycoords='axes fraction', textcoords='offset points')

    # credit to https://stackoverflow.com/questions/4700614/how-to-put-the-legend-out-of-the-plot
    # Shrink current axis by 20%
    box = ax.get_position()
    #ax.set_position([box.x0, box.y0, box.width * 0.85, box.height])
    # Put a legend to the right of the current axis
    #ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))

    #plt.show()
    plt.savefig(output_file, dpi=600)



genomes_table_files = namedtuple('genomes_table_files', ['vcfeval_dir', 'vcfstats_genome', 'vcfstats_outside_GIAB', 'runtime'])
genomes_table_entry = namedtuple('genomes_table_entry', ['SNVs_called', 'precision', 'recall', 'outside_GIAB', 'runtime'])

def get_snp_count(vcfstats_file):
    passed_re = re.compile("\nPassed Filters\s+: (\d+)\n")
    snps_re = re.compile("\nSNPs\s+: (-|\d+)\n")
    with open(vcfstats_file,'r') as inf:
        fstr = inf.read()
        if int(passed_re.findall(fstr)[0]) == 0:
            return 0
        else:
            return int(snps_re.findall(fstr)[0])

def get_TsTv(vcfstats_file):
    tstv_re = re.compile("\nSNP Transitions/Transversions: (-|\d+\.\d+)\s+")
    with open(vcfstats_file,'r') as inf:
        fstr = inf.read()
        res = tstv_re.findall(fstr)[0]
        if res == '-':
            return 0.0
        else:
            return float(res)

def make_table_4_genomes_pacbio_illumina(NA12878_30x_table_files, NA12878_44x_table_files,
                                  NA24385_30x_table_files,
                                  NA24385_40x_table_files, NA24385_50x_table_files,
                                  NA24385_69x_table_files,
                                  NA24149_32x_table_files,
                                  NA24143_30x_table_files,
                                  gq_cutoffs, coverages,
                                  outfile):

    def generate_table_line(table_files, gq_cutoff):

        precision, recall = get_precision_recall(table_files.vcfeval_dir, gq_cutoff)
        with open(table_files.runtime,'r') as inf:
            hh, mm, ss = inf.readline().strip().split(':')
        runtime = hh + ':' + mm

        snvs_total = get_snp_count(table_files.vcfstats_genome)
        snvs_outside_giab = get_snp_count(table_files.vcfstats_outside_GIAB)

        return genomes_table_entry(SNVs_called=snvs_total, precision=precision, recall=recall,
                                   outside_GIAB=snvs_outside_giab, runtime=runtime)

    NA12878_30x = generate_table_line(NA12878_30x_table_files, gq_cutoffs[0])
    NA12878_44x = generate_table_line(NA12878_44x_table_files, gq_cutoffs[1])

    NA24385_30x = generate_table_line(NA24385_30x_table_files, gq_cutoffs[2])
    NA24385_40x = generate_table_line(NA24385_40x_table_files, gq_cutoffs[3])
    NA24385_50x = generate_table_line(NA24385_50x_table_files, gq_cutoffs[4])
    NA24385_69x = generate_table_line(NA24385_69x_table_files, gq_cutoffs[5])

    NA24149_32x = generate_table_line(NA24149_32x_table_files, gq_cutoffs[6])
    NA24143_30x = generate_table_line(NA24143_30x_table_files, gq_cutoffs[7])

    s = '''
\\begin{{table}}[htbp]
\\centering
\\begin{{tabular}}{{lllllll}}
\\hline
Genome      & Read & SNVs    & Precision     & Recall    & Outside GIAB  & Run time  \\\\
            & Coverage & called    &    &  & high-confidence       & (hours:minutes)          \\\\
\\hline
NA12878   & ${}\\times$ & {} & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA12878   & ${}\\times$ & {} & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24385 (AJ son) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24385 (AJ son) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24385 (AJ son) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24385 (AJ son) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24149 (AJ father) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24143 (AJ mother) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
\\hline
\\end{{tabular}}
\\caption{{{{\\bf Summary of variants called on GIAB genomes.}}}}
\\label{{tab:stats}}
\\end{{table}}
'''.format(coverages[0], NA12878_30x.SNVs_called, NA12878_30x.precision, NA12878_30x.recall, NA12878_30x.outside_GIAB, NA12878_30x.runtime,
           coverages[1], NA12878_44x.SNVs_called, NA12878_44x.precision, NA12878_44x.recall, NA12878_44x.outside_GIAB, NA12878_44x.runtime,
           coverages[2], NA24385_30x.SNVs_called, NA24385_30x.precision, NA24385_30x.recall, NA24385_30x.outside_GIAB, NA24385_30x.runtime,
           coverages[3], NA24385_40x.SNVs_called, NA24385_40x.precision, NA24385_40x.recall, NA24385_40x.outside_GIAB, NA24385_40x.runtime,
           coverages[4], NA24385_50x.SNVs_called, NA24385_50x.precision, NA24385_50x.recall, NA24385_50x.outside_GIAB, NA24385_50x.runtime,
           coverages[5], NA24385_69x.SNVs_called, NA24385_69x.precision, NA24385_69x.recall, NA24385_69x.outside_GIAB, NA24385_69x.runtime,
           coverages[6], NA24149_32x.SNVs_called, NA24149_32x.precision, NA24149_32x.recall, NA24149_32x.outside_GIAB, NA24149_32x.runtime,
           coverages[7], NA24143_30x.SNVs_called, NA24143_30x.precision, NA24143_30x.recall, NA24143_30x.outside_GIAB, NA24143_30x.runtime)

    with open(outfile,'w') as outf:
        print(s, file=outf)


def make_table_4_genomes_extended(NA12878_30x_table_files, NA12878_44x_table_files,
                                  NA24385_30x_table_files,
                                  NA24385_40x_table_files, NA24385_50x_table_files,
                                  NA24385_69x_table_files,
                                  NA24149_32x_table_files,
                                  NA24143_30x_table_files,
                                  gq_cutoffs, coverages,
                                  outfile):

    def generate_table_line(table_files, gq_cutoff):

        precision, recall = get_precision_recall(table_files.vcfeval_dir, gq_cutoff)
        with open(table_files.runtime,'r') as inf:
            hh, mm, ss = inf.readline().strip().split(':')
        runtime = hh + ':' + mm

        snvs_total = get_snp_count(table_files.vcfstats_genome)
        snvs_outside_giab = get_snp_count(table_files.vcfstats_outside_GIAB)

        return genomes_table_entry(SNVs_called=snvs_total, precision=precision, recall=recall,
                                   outside_GIAB=snvs_outside_giab, runtime=runtime)

    NA12878_30x = generate_table_line(NA12878_30x_table_files, gq_cutoffs[0])
    NA12878_44x = generate_table_line(NA12878_44x_table_files, gq_cutoffs[1])

    NA24385_30x = generate_table_line(NA24385_30x_table_files, gq_cutoffs[2])
    NA24385_40x = generate_table_line(NA24385_40x_table_files, gq_cutoffs[3])
    NA24385_50x = generate_table_line(NA24385_50x_table_files, gq_cutoffs[4])
    NA24385_69x = generate_table_line(NA24385_69x_table_files, gq_cutoffs[5])

    NA24149_32x = generate_table_line(NA24149_32x_table_files, gq_cutoffs[6])
    NA24143_30x = generate_table_line(NA24143_30x_table_files, gq_cutoffs[7])

    s = '''
\\begin{{table}}[htbp]
\\centering
\\begin{{tabular}}{{lllllll}}
\\hline
Genome      & Read & SNVs    & Precision     & Recall    & Outside GIAB  & Run time  \\\\
            & Coverage & called    &    &  & high-confidence       & (hours)          \\\\
\\hline
NA12878   & ${}\\times$ & {} & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA12878   & ${}\\times$ & {} & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24385 (AJ son) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24385 (AJ son) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24385 (AJ son) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24385 (AJ son) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24149 (AJ father) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
NA24143 (AJ mother) & ${}\\times$ & ${}$ & ${:.3f}$ & ${:.3f}$ & ${}$ & {} \\\\
\\hline
\\end{{tabular}}
\\caption{{{{\\bf Summary of variants called on GIAB genomes.}}}}
\\label{{tab:stats}}
\\end{{table}}
'''.format(coverages[0], NA12878_30x.SNVs_called, NA12878_30x.precision, NA12878_30x.recall, NA12878_30x.outside_GIAB, NA12878_30x.runtime,
           coverages[1], NA12878_44x.SNVs_called, NA12878_44x.precision, NA12878_44x.recall, NA12878_44x.outside_GIAB, NA12878_44x.runtime,
           coverages[2], NA24385_30x.SNVs_called, NA24385_30x.precision, NA24385_30x.recall, NA24385_30x.outside_GIAB, NA24385_30x.runtime,
           coverages[3], NA24385_40x.SNVs_called, NA24385_40x.precision, NA24385_40x.recall, NA24385_40x.outside_GIAB, NA24385_40x.runtime,
           coverages[4], NA24385_50x.SNVs_called, NA24385_50x.precision, NA24385_50x.recall, NA24385_50x.outside_GIAB, NA24385_50x.runtime,
           coverages[5], NA24385_69x.SNVs_called, NA24385_69x.precision, NA24385_69x.recall, NA24385_69x.outside_GIAB, NA24385_69x.runtime,
           coverages[6], NA24149_32x.SNVs_called, NA24149_32x.precision, NA24149_32x.recall, NA24149_32x.outside_GIAB, NA24149_32x.runtime,
           coverages[7], NA24143_30x.SNVs_called, NA24143_30x.precision, NA24143_30x.recall, NA24143_30x.outside_GIAB, NA24143_30x.runtime)

    with open(outfile,'w') as outf:
        print(s, file=outf)


MAX_DEPTH = 50
def plot_depth_of_mapped_vs_breadth(inputs, labels, colors, output_file):

    plt.figure(figsize=(6,6))
    ax = plt.subplot(111)

    def get_depth_breadth(histogram_file):
        breadth = defaultdict(int)
        chr_sizes = dict()
        with open(histogram_file,'r') as infile:
            for line in infile:
                el = line.strip().split('\t')

                chrom = el[0]
                depth = int(el[1])
                num_bases = int(el[2])
                chr_size = int(el[3])
                if chrom in chr_sizes:
                    assert(chr_sizes[chrom] == chr_size)
                else:
                    chr_sizes[chrom] = chr_size

                if depth > MAX_DEPTH:
                    depth = MAX_DEPTH
                breadth[depth] += num_bases

        # cumulative breadth
        cml_breadth = defaultdict(int)

        # sorted (depth, breadth) pairs
        s_breadth = sorted(list(breadth.items()))

        for d, b in s_breadth:
            for d2,b2 in s_breadth:
                if d2 >= d:
                    cml_breadth[d] += b2

        d_val = []
        b_frac = []
        genome_len = sum(chr_sizes.values())*1.0
        # sorted cumulative breadth
        for d in range(0,51):
            d_val.append(d)
            b_frac.append(cml_breadth[d]/genome_len)
        #for d, b in sorted(list(cml_breadth.items())):
        #    d_val.append(d)
        #    b_frac.append(b/genome_len)

        return d_val, b_frac

    for input,label,color in zip(inputs, labels, colors):
        #if 'mapq0' not in input and 'mapq30' not in input:
        #    continue
        d_val, b_frac = get_depth_breadth(input)
        print(label + ':')
        print("depth\tbreadth")
        for d,b in zip(d_val, b_frac):
            print("{}\t{}".format(d, b))
        print("")
        plt.plot(d_val,b_frac,color=color,label=label)

    plt.grid(True,color='grey',linestyle='--',alpha=0.5)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["bottom"].set_visible(False)
    ax.spines["left"].set_visible(False)
    plt.tick_params(axis="both", which="both", bottom="off", top="off",
                labelbottom="on", left="off", right="off", labelleft="on")

    plt.xlabel('Recall')
    plt.ylabel('Precision')

    plt.legend(loc='lower left')
    plt.xlabel('Minimum Depth of Mapped Reads')
    plt.ylabel('Fraction of Genome Covered')
    plt.tight_layout()

    plt.savefig(output_file, dpi = 600)

def make_variant_counts_table(chr1_22_region_size_file,
                              segmental_duplications_95_region_size_file,
                              segmental_duplications_99_region_size_file,
                              confident_region_size_file,
                              nonconfident_region_size_file,
                              illumina_genome_stats,
                              illumina_segdup95_stats,
                              illumina_segdup99_stats,
                              illumina_GIAB_confident_stats,
                              illumina_GIAB_nonconfident_stats,
                              pacbio_genome_stats,
                              pacbio_segdup95_stats,
                              pacbio_segdup99_stats,
                              pacbio_GIAB_confident_stats,
                              pacbio_GIAB_nonconfident_stats,
                              pacbio_minus_illumina_genome_stats,
                              pacbio_minus_illumina_segdup95_stats,
                              pacbio_minus_illumina_segdup99_stats,
                              pacbio_minus_illumina_GIAB_confident_stats,
                              pacbio_minus_illumina_GIAB_nonconfident_stats,
                              illumina_minus_pacbio_genome_stats,
                              illumina_minus_pacbio_segdup95_stats,
                              illumina_minus_pacbio_segdup99_stats,
                              illumina_minus_pacbio_GIAB_confident_stats,
                              illumina_minus_pacbio_GIAB_nonconfident_stats,
                              intersect_illumina_pacbio_genome_stats,
                              intersect_illumina_pacbio_segdup95_stats,
                              intersect_illumina_pacbio_segdup99_stats,
                              intersect_illumina_pacbio_GIAB_confident_stats,
                              intersect_illumina_pacbio_GIAB_nonconfident_stats,
                              outfile):


    def read_region_size(region_size_file):
        with open(region_size_file,'r') as inf:
            return int(inf.readline().strip())

    # read in files containing bed file total lengths
    chr1_22_region_size = read_region_size(chr1_22_region_size_file)
    segmental_duplications_95_region_size = read_region_size(segmental_duplications_95_region_size_file)
    segmental_duplications_99_region_size = read_region_size(segmental_duplications_99_region_size_file)
    confident_region_size = read_region_size(confident_region_size_file)
    nonconfident_region_size = read_region_size(nonconfident_region_size_file)

    # TsTv and num SNVs for illumina short reads
    illumina_genome_TsTv = get_TsTv(illumina_genome_stats)
    illumina_genome_numSNVs = get_snp_count(illumina_genome_stats)

    illumina_segdup95_TsTv = get_TsTv(illumina_segdup95_stats)
    illumina_segdup95_numSNVs = get_snp_count(illumina_segdup95_stats)

    illumina_segdup99_TsTv = get_TsTv(illumina_segdup99_stats)
    illumina_segdup99_numSNVs = get_snp_count(illumina_segdup99_stats)

    illumina_GIAB_confident_TsTv = get_TsTv(illumina_GIAB_confident_stats)
    illumina_GIAB_confident_numSNVs = get_snp_count(illumina_GIAB_confident_stats)

    illumina_GIAB_nonconfident_TsTv = get_TsTv(illumina_GIAB_nonconfident_stats)
    illumina_GIAB_nonconfident_numSNVs = get_snp_count(illumina_GIAB_nonconfident_stats)


    # TsTv and num SNVs for pacbio long reads
    pacbio_genome_TsTv = get_TsTv(pacbio_genome_stats)
    pacbio_genome_numSNVs = get_snp_count(pacbio_genome_stats)

    pacbio_segdup95_TsTv = get_TsTv(pacbio_segdup95_stats)
    pacbio_segdup95_numSNVs = get_snp_count(pacbio_segdup95_stats)

    pacbio_segdup99_TsTv = get_TsTv(pacbio_segdup99_stats)
    pacbio_segdup99_numSNVs = get_snp_count(pacbio_segdup99_stats)

    pacbio_GIAB_confident_TsTv = get_TsTv(pacbio_GIAB_confident_stats)
    pacbio_GIAB_confident_numSNVs = get_snp_count(pacbio_GIAB_confident_stats)

    pacbio_GIAB_nonconfident_TsTv = get_TsTv(pacbio_GIAB_nonconfident_stats)
    pacbio_GIAB_nonconfident_numSNVs = get_snp_count(pacbio_GIAB_nonconfident_stats)

    # TsTv and num SNVs for SNVs unique to pacbio
    pacbio_minus_illumina_genome_TsTv = get_TsTv(pacbio_minus_illumina_genome_stats)
    pacbio_minus_illumina_genome_numSNVs = get_snp_count(pacbio_minus_illumina_genome_stats)

    pacbio_minus_illumina_segdup95_TsTv = get_TsTv(pacbio_minus_illumina_segdup95_stats)
    pacbio_minus_illumina_segdup95_numSNVs = get_snp_count(pacbio_minus_illumina_segdup95_stats)

    pacbio_minus_illumina_segdup99_TsTv = get_TsTv(pacbio_minus_illumina_segdup99_stats)
    pacbio_minus_illumina_segdup99_numSNVs = get_snp_count(pacbio_minus_illumina_segdup99_stats)

    pacbio_minus_illumina_GIAB_confident_TsTv = get_TsTv(pacbio_minus_illumina_GIAB_confident_stats)
    pacbio_minus_illumina_GIAB_confident_numSNVs = get_snp_count(pacbio_minus_illumina_GIAB_confident_stats)

    pacbio_minus_illumina_GIAB_nonconfident_TsTv = get_TsTv(pacbio_minus_illumina_GIAB_nonconfident_stats)
    pacbio_minus_illumina_GIAB_nonconfident_numSNVs = get_snp_count(pacbio_minus_illumina_GIAB_nonconfident_stats)

    # TsTv and num SNVs for SNVs unique to illumina
    illumina_minus_pacbio_genome_TsTv = get_TsTv(illumina_minus_pacbio_genome_stats)
    illumina_minus_pacbio_genome_numSNVs = get_snp_count(illumina_minus_pacbio_genome_stats)

    illumina_minus_pacbio_segdup95_TsTv = get_TsTv(illumina_minus_pacbio_segdup95_stats)
    illumina_minus_pacbio_segdup95_numSNVs = get_snp_count(illumina_minus_pacbio_segdup95_stats)

    illumina_minus_pacbio_segdup99_TsTv = get_TsTv(illumina_minus_pacbio_segdup99_stats)
    illumina_minus_pacbio_segdup99_numSNVs = get_snp_count(illumina_minus_pacbio_segdup99_stats)

    illumina_minus_pacbio_GIAB_confident_TsTv = get_TsTv(illumina_minus_pacbio_GIAB_confident_stats)
    illumina_minus_pacbio_GIAB_confident_numSNVs = get_snp_count(illumina_minus_pacbio_GIAB_confident_stats)

    illumina_minus_pacbio_GIAB_nonconfident_TsTv = get_TsTv(illumina_minus_pacbio_GIAB_nonconfident_stats)
    illumina_minus_pacbio_GIAB_nonconfident_numSNVs = get_snp_count(illumina_minus_pacbio_GIAB_nonconfident_stats)

    # TsTv and num SNVs for intersection of illumina and pacbio long reads
    intersect_illumina_pacbio_genome_TsTv = get_TsTv(intersect_illumina_pacbio_genome_stats)
    intersect_illumina_pacbio_genome_numSNVs = get_snp_count(intersect_illumina_pacbio_genome_stats)

    intersect_illumina_pacbio_segdup95_TsTv = get_TsTv(intersect_illumina_pacbio_segdup95_stats)
    intersect_illumina_pacbio_segdup95_numSNVs = get_snp_count(intersect_illumina_pacbio_segdup95_stats)

    intersect_illumina_pacbio_segdup99_TsTv = get_TsTv(intersect_illumina_pacbio_segdup99_stats)
    intersect_illumina_pacbio_segdup99_numSNVs = get_snp_count(intersect_illumina_pacbio_segdup99_stats)

    intersect_illumina_pacbio_GIAB_confident_TsTv = get_TsTv(intersect_illumina_pacbio_GIAB_confident_stats)
    intersect_illumina_pacbio_GIAB_confident_numSNVs = get_snp_count(intersect_illumina_pacbio_GIAB_confident_stats)

    intersect_illumina_pacbio_GIAB_nonconfident_TsTv = get_TsTv(intersect_illumina_pacbio_GIAB_nonconfident_stats)
    intersect_illumina_pacbio_GIAB_nonconfident_numSNVs = get_snp_count(intersect_illumina_pacbio_GIAB_nonconfident_stats)

    s = '''
\\begin{{table}}[htbp]
\\centering
\\small
\\begin{{tabular}}{{lllllll}}
\\hline
                                                                        &                        & Genome  & Inside GIAB & Outside GIAB & Segmental Dup.       & Segmental Dup.       \\\\
                                                                        &                        & (1-22)  & Confident   & Confident    & ($\geq 95\%$ similar)& ($\geq 99\%$ similar)\\\\
\\hline
Region size                                                             &                        & {}      & {}          & {}           & {}                   & {}                   \\tabularnewline
\\cellcolor[gray]{{0.9}}                                                &\\cellcolor[gray]{{0.9}}\# SNVs                &\\cellcolor[gray]{{0.9}}{:,}    &\\cellcolor[gray]{{0.9}}{:,}        &\\cellcolor[gray]{{0.9}}{:,}         &\\cellcolor[gray]{{0.9}}{:,}                 &\\cellcolor[gray]{{0.9}}{:,}                 \\tabularnewline
\\multirow{{-2}}{{*}}{{\\cellcolor[gray]{{0.9}}PacBio}}               &\\cellcolor[gray]{{0.9}}Ts/Tv &\\cellcolor[gray]{{0.9}}{}      &\\cellcolor[gray]{{0.9}}{}          &\\cellcolor[gray]{{0.9}}{}           &\\cellcolor[gray]{{0.9}}{}                   &\\cellcolor[gray]{{0.9}}{}                   \\tabularnewline
                                                                        & \# SNVs                & {:,}    & {:,}        & {:,}         & {:,}                 & {:,}                 \\tabularnewline
\\multirow{{-2}}{{*}}{{Illumina}}                                         & Ts/Tv                  & {}      & {}          & {}           & {}                   & {}                   \\tabularnewline
\\cellcolor[gray]{{0.9}}                                                      &\\cellcolor[gray]{{0.9}}\# SNVs                &\\cellcolor[gray]{{0.9}}{:,}    &\\cellcolor[gray]{{0.9}}{:,}        &\\cellcolor[gray]{{0.9}}{:,}         &\\cellcolor[gray]{{0.9}}{:,}                 &\\cellcolor[gray]{{0.9}}{:,}                 \\tabularnewline
\\multirow{{-2}}{{*}}{{\\cellcolor[gray]{{0.9}}Unique to PacBio}}       &\\cellcolor[gray]{{0.9}}Ts/Tv &\\cellcolor[gray]{{0.9}}{}      &\\cellcolor[gray]{{0.9}}{}          &\\cellcolor[gray]{{0.9}}{}           &\\cellcolor[gray]{{0.9}}{}                   &\\cellcolor[gray]{{0.9}}{}                   \\tabularnewline
                                                      &  \# SNVs                &  {:,}    &  {:,}        &  {:,}         &  {:,}                 &  {:,}                 \\tabularnewline
\\multirow{{-2}}{{*}}{{Unique to Illumina}}       & Ts/Tv & {}      &  {}          &  {}           &  {}                   &  {}                   \\tabularnewline
\\cellcolor[gray]{{0.9}}Shared                                         &\\cellcolor[gray]{{0.9}}\# SNVs                &\\cellcolor[gray]{{0.9}}{:,}    &\\cellcolor[gray]{{0.9}}{:,}        &\\cellcolor[gray]{{0.9}}{:,}         &\\cellcolor[gray]{{0.9}}{:,}                 &\\cellcolor[gray]{{0.9}}{:,}                 \\tabularnewline
\\cellcolor[gray]{{0.9}}Illumina \\& PacBio                             &\\cellcolor[gray]{{0.9}}Ts/Tv                  &\\cellcolor[gray]{{0.9}}{}      &\\cellcolor[gray]{{0.9}}{}          &\\cellcolor[gray]{{0.9}}{}           &\\cellcolor[gray]{{0.9}}{}                   &\\cellcolor[gray]{{0.9}}{}                   \\tabularnewline
\\hline
\\end{{tabular}}
\\caption{{{{\\bf Number of variants called for NA12878 in various genomic regions with short reads ($\mathbf{{30\\times}}$ coverage) and long reads ($\mathbf{{44\\times}}$ coverage).
Statistics are also shown for the variants unique to each technology and the variants shared by both.}}}}
\\label{{tab:variant_counts}}
\\end{{table}}
'''.format(format_bp(chr1_22_region_size), format_bp(confident_region_size), format_bp(nonconfident_region_size), format_bp(segmental_duplications_95_region_size), format_bp(segmental_duplications_99_region_size),
           pacbio_genome_numSNVs, pacbio_GIAB_confident_numSNVs, pacbio_GIAB_nonconfident_numSNVs, pacbio_segdup95_numSNVs, pacbio_segdup99_numSNVs,
           pacbio_genome_TsTv, pacbio_GIAB_confident_TsTv, pacbio_GIAB_nonconfident_TsTv, pacbio_segdup95_TsTv, pacbio_segdup99_TsTv,
           illumina_genome_numSNVs, illumina_GIAB_confident_numSNVs, illumina_GIAB_nonconfident_numSNVs, illumina_segdup95_numSNVs, illumina_segdup99_numSNVs,
           illumina_genome_TsTv, illumina_GIAB_confident_TsTv, illumina_GIAB_nonconfident_TsTv, illumina_segdup95_TsTv, illumina_segdup99_TsTv,
           pacbio_minus_illumina_genome_numSNVs, pacbio_minus_illumina_GIAB_confident_numSNVs, pacbio_minus_illumina_GIAB_nonconfident_numSNVs, pacbio_minus_illumina_segdup95_numSNVs, pacbio_minus_illumina_segdup99_numSNVs,
           pacbio_minus_illumina_genome_TsTv, pacbio_minus_illumina_GIAB_confident_TsTv, pacbio_minus_illumina_GIAB_nonconfident_TsTv, pacbio_minus_illumina_segdup95_TsTv, pacbio_minus_illumina_segdup99_TsTv,
           illumina_minus_pacbio_genome_numSNVs, illumina_minus_pacbio_GIAB_confident_numSNVs, illumina_minus_pacbio_GIAB_nonconfident_numSNVs, illumina_minus_pacbio_segdup95_numSNVs, illumina_minus_pacbio_segdup99_numSNVs,
           illumina_minus_pacbio_genome_TsTv, illumina_minus_pacbio_GIAB_confident_TsTv, illumina_minus_pacbio_GIAB_nonconfident_TsTv, illumina_minus_pacbio_segdup95_TsTv, illumina_minus_pacbio_segdup99_TsTv,
           intersect_illumina_pacbio_genome_numSNVs, intersect_illumina_pacbio_GIAB_confident_numSNVs, intersect_illumina_pacbio_GIAB_nonconfident_numSNVs, intersect_illumina_pacbio_segdup95_numSNVs, intersect_illumina_pacbio_segdup99_numSNVs,
           intersect_illumina_pacbio_genome_TsTv, intersect_illumina_pacbio_GIAB_confident_TsTv, intersect_illumina_pacbio_GIAB_nonconfident_TsTv,  intersect_illumina_pacbio_segdup95_TsTv, intersect_illumina_pacbio_segdup99_TsTv)

    with open(outfile,'w') as outf:
        print(s, file=outf)


def plot_fp_near_indel(fp_vcfs, fixed_gq_VCFstats, scaled_gq_VCFstats, ground_truth,
                       output_png, cov, fixed_gq, scaled_gqs):

    fixed_gq_fp = []
    scaled_gq_fp = []

    for fp_vcf, fixed_gq_VCFstat, scaled_gq_VCFstat, scaled_gq in zip(fp_vcfs, fixed_gq_VCFstats, scaled_gq_VCFstats, scaled_gqs):

        fixed_gq_count = count_fp_near_true_indel(fp_vcf, ground_truth, fixed_gq)
        scaled_gq_count = count_fp_near_true_indel(fp_vcf, ground_truth, scaled_gq)

        # count the total # of SNVs called at this cutoff
        fixed_gq_total = get_snp_count(fixed_gq_VCFstat)
        scaled_gq_total = get_snp_count(scaled_gq_VCFstat)

        fixed_gq_fp.append(fixed_gq_count / fixed_gq_total)
        scaled_gq_fp.append(scaled_gq_count / scaled_gq_total)

    plt.figure();
    ax1 = plt.subplot(111)

    plt.plot(cov, fixed_gq_fp, color='r',label='Fixed GQ={}'.format(fixed_gq),linewidth=3,alpha=0.75)
    plt.plot(cov, scaled_gq_fp, color='b',label='Coverage Scaled GQ',linewidth=3,alpha=0.75)

    plt.grid(True,color='grey',linestyle='--',alpha=0.5)

    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)
    ax1.spines["bottom"].set_visible(False)
    ax1.spines["left"].set_visible(False)
    plt.tick_params(axis="both", which="both", bottom="off", top="off",
                labelbottom="on", left="off", right="off", labelleft="on")

    #plt.xlim(xlim)
    #plt.ylim(ylim)
    plt.xlabel('Read Coverage')
    plt.ylabel('Rate of FP SNVs at true indel sites')
    plt.legend(loc='upper left')
    plt.tight_layout()
    ax1.set_axisbelow(True)
    plt.savefig(output_png, dpi = 600)

def actual_to_effective_read_coverage_plot(vcfgz_file, output_file):

    actual = []
    effective = []
    with pysam.VariantFile(vcfgz_file) as vcf:
        for rec in vcf:

            ac = sum(rec.info['AC']) + rec.info['AM'] #rec.info['DP']
            ef = sum(rec.info['AC'])
            actual.append(ac)
            effective.append(ef)

    d = defaultdict(list)
    for a,e in zip(actual, effective):
        d[a].append(e)

    medians_x = []
    medians_y = []
    Q1 = []
    Q3 = []

    for a, lst in sorted(list(d.items())):
        medians_x.append(a)
        medians_y.append(statistics.median(lst))
        Q1.append(np.percentile(lst, 25))
        Q3.append(np.percentile(lst, 75))

    plt.figure()
    #import pdb; pdb.set_trace()
    #data = pd.DataFrame(
    #{'Actual read coverage': actual,
    # 'Effective read coverage': effective,
    #})
    #ax = sns.jointplot(data=data,x='Actual read coverage',y='Effective read coverage', color='k', kind='hex')
    ax1 = plt.subplot(111)

    plt.grid(True,color='grey',linestyle='--',alpha=0.5)

    #plt.scatter(actual, effective, color='b',marker='.',s=1,alpha=0.75,label='Single variant site')

    plt.plot([min(medians_x),max(medians_x)], [min(medians_x),max(medians_x)], color='k',linestyle=':',alpha=0.75,linewidth=3,label=None)
    plt.fill_between(medians_x, Q1, Q3, color='r',alpha=0.3)#,label='1st-3rd Quartiles')
    plt.plot(medians_x, medians_y, color='r',alpha=0.75,linewidth=3)#,label='Median effective coverage')

    ax1.spines["top"].set_visible(False)
    ax1.spines["right"].set_visible(False)
    ax1.spines["bottom"].set_visible(False)
    ax1.spines["left"].set_visible(False)
    plt.tick_params(axis="both", which="both", bottom="off", top="off",
                labelbottom="on", left="off", right="off", labelleft="on")

    #plt.legend(loc='upper left')
    plt.xlabel('Actual Read Coverage')
    plt.ylabel('Effective Read Coverage')
    plt.tight_layout()
    plt.savefig(output_file, dpi = 600)


def plot_mappability_bars(pacbio_mf_0_0,
                          pacbio_mf_0_5,
                          pacbio_mf_0_75,
                          pacbio_mf_0_9,
                          pacbio_mf_1_0,
                          illumina_mf_0_0,
                          illumina_mf_0_5,
                          illumina_mf_0_75,
                          illumina_mf_0_9,
                          illumina_mf_1_0,
                          output_file,
                          total_nonN_bases):

    plt.figure(figsize=(8.5,4))
    #mpl.rcParams['axes.titlepad'] = 50
    ax = plt.subplot(111)
    plt.ylim((0.9,1.0))

    subplots_adjust_frac = 0.82
    width = 0.005
    alpha1 = 0.6

    #ind = np.array([0,0.04,0.08,0.12,0.16])
    ind = np.array([0,0.04,0.08])

    def parse_datafile_lst(datafile_lst):
        lst = []

        for datafile in datafile_lst:
            with open(datafile,'r') as inf:
                num_positions = float(inf.readline().strip())
                lst.append(num_positions / total_nonN_bases)

        return lst

    pacbio_mf_0_0_data = parse_datafile_lst(pacbio_mf_0_0)
    pacbio_mf_0_5_data = parse_datafile_lst(pacbio_mf_0_5)
    pacbio_mf_0_75_data = parse_datafile_lst(pacbio_mf_0_75)
    pacbio_mf_0_9_data = parse_datafile_lst(pacbio_mf_0_9)
    pacbio_mf_1_0_data = parse_datafile_lst(pacbio_mf_1_0)
    illumina_mf_0_0_data = parse_datafile_lst(illumina_mf_0_0)
    illumina_mf_0_5_data = parse_datafile_lst(illumina_mf_0_5)
    illumina_mf_0_75_data = parse_datafile_lst(illumina_mf_0_75)
    illumina_mf_0_9_data = parse_datafile_lst(illumina_mf_0_9)
    illumina_mf_1_0_data = parse_datafile_lst(illumina_mf_1_0)

    # credit for this function: http://composition.al/blog/2015/11/29/a-better-way-to-add-labels-to-bar-charts-with-matplotlib/
    def autolabel(rects, ax, height_fmt_string="{0:.4f}"):
        # Get y-axis height to calculate label position from.
        (y_bottom, y_top) = ax.get_ylim()
        y_height = y_top - y_bottom

        for rect in rects:
            height = rect.get_height()

            label_position = height + (y_height * 0.01)

            ax.text(rect.get_x() + rect.get_width()/2., label_position,
                    height_fmt_string.format(height),
                    ha='center', va='bottom', fontsize=6)

    def plot_bars(ax, vals,color,ix,lab):
        rects = plt.bar(ind+ix*width, vals, color=color,
                ecolor='black', # black error bar color
                alpha=alpha1,      # transparency
                width=width,      # smaller bar width
                align='center',
                label=lab,
                zorder=0)
        autolabel(rects,ax)

    print("PacBio map fraction 0.5 data:")
    print("20 30 40")
    print(pacbio_mf_0_5_data)
    print("")

    print("PacBio map fraction 0.75 data:")
    print("20 30 40")
    print(pacbio_mf_0_75_data)
    print("")

    print("PacBio map fraction 0.9 data:")
    print("20 30 40")
    print(pacbio_mf_0_9_data)
    print("")

    print("illumina map fraction 0.5 data:")
    print("20 30 40")
    print(illumina_mf_0_5_data)
    print("")

    print("illumina map fraction 0.75 data:")
    print("20 30 40")
    print(illumina_mf_0_75_data)
    print("")

    print("illumina map fraction 0.9 data:")
    print("20 30 40")
    print(illumina_mf_0_9_data)
    print("")

    #plot_bars(pacbio_mf_0_0_data,'#c3d6f4',0,'PacBio, all sites')
    plot_bars(ax, pacbio_mf_0_5_data,'#93bcff',1,'PacBio, at least 50% well-mapped')
    plot_bars(ax, pacbio_mf_0_75_data,'#609dff',2,'PacBio, at least 75% well-mapped')
    plot_bars(ax, pacbio_mf_0_9_data,'#3582ff',3,'PacBio, at least 90% well-mapped')
    #plot_bars(pacbio_mf_1_0_data,'#0061ff',4,'PacBio, 100% well-mapped')

    #plot_bars(illumina_mf_0_0_data,'#ffa0a0',5,'Illumina, all sites')
    plot_bars(ax, illumina_mf_0_5_data,'#ff7272',4,'Illumina, at least 50% well-mapped')
    plot_bars(ax, illumina_mf_0_75_data,'#ff4242',5,'Illumina, at least 75% well-mapped')
    plot_bars(ax, illumina_mf_0_9_data,'#ff2323',6,'Illumina, at least 90% well-mapped')
    #plot_bars(illumina_mf_1_0_data,'#ff0000',9,'Illumina, 100% well-mapped')

    ax.yaxis.grid(True,color='grey', alpha=0.5, linestyle='--',zorder=1.0)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["bottom"].set_visible(False)
    ax.spines["left"].set_visible(False)
    plt.tick_params(axis="both", which="both", bottom=False, top=False,
                labelbottom=True, left=False, right=False, labelleft=True)

    ax.set_xticks(ind+3.5*width)
    ax.set_xticklabels(['20' + r'$\times$','30' + r'$\times$','40' + r'$\times$'])

    plt.xlabel('Minimum read coverage')
    plt.ylabel('Fraction of genome covered (chr. 1-22)')
    ax.legend(loc='center left', bbox_to_anchor=(0.1,1.25),ncol=2)
    plt.subplots_adjust(top=subplots_adjust_frac)
    plt.tight_layout()

    ax.set_axisbelow(True)

    ticklabelpad = mpl.rcParams['xtick.major.pad']

    #ax.annotate('coverage', xy=(-0.1,-0.03), xytext=(5, -ticklabelpad), ha='left', va='top',
    #            xycoords='axes fraction', textcoords='offset points')

    plt.savefig(output_file, dpi = 600)

def mendelian_concordance_table(pacbio_row, outfile, include_count=False):

    consistency_re = re.compile("\s+F\+M:\d+\/\d+\s+\((\d+\.\d+%)\)\n")
    count_re = re.compile("\s+F\+M:(\d+)\/\d+\s+\(\d+\.\d+%\)\n")

    def parse_mendelian_output(mendelian_output):
        with open(mendelian_output,'r') as inf:
            file_contents = inf.read()
            if include_count:
                return count_re.findall(file_contents)[0] + ', ' + consistency_re.findall(file_contents)[0]
            else:
                return consistency_re.findall(file_contents)[0]

    pacbio_data = [parse_mendelian_output(f).replace('%','\%') for f in pacbio_row]

    # read in files containing bed file total lengths

    s = '''
\\begin{{table}}[htbp]
\\centering
\\small
\\begin{{tabular}}{{lllll}}
\\hline
         & Genome  & Inside GIAB & Outside GIAB & Segmental Dup.       \\\\
         & (1-22)  & Confident   & Confident    & ($\geq 95\%$ similar)\\\\
\\hline
PacBio   & {}      & {}          & {}           & {}                   \\tabularnewline
\\hline
\\end{{tabular}}
\\caption{{{{\\bf Mendelian consistency for AJ Trio between variants called using PacBio reads
($\\mathbf{{69\\times}}$ coverage son, $\\mathbf{{30\\times}}$ coverage mother, $\\mathbf{{32\\times}}$ coverage father),
Results are shown for genome-wide variants as well as variants within specific genomic regions.}}}}
\\label{{tab:mendelian}}
\\end{{table}}
'''.format(*pacbio_data)

    with open(outfile,'w') as outf:
        print(s, file=outf)

def make_dup_gene_table(gene_names, regions, pb_SNV_stats, il_SNV_stats, shared_SNV_stats, pb_frac_map, il_frac_map, output_file):

    def parse_file(infile):
        with open(infile,'r') as inf:
            return inf.read().strip()

    with open(output_file,'w') as outf:

        head_part = '''\\begin{table}[htbp]
\\centering
\\small
\\begin{tabular}{lllllll}
\\hline
Gene & Region & \# SNVs & \# SNVs   & \# SNVs & \% Mappable  & \% Mappable \\\\
Name &        & PacBio  & Illumina  & Shared  & PacBio       &  Illumina   \\\\
\\hline'''

        print(head_part,file=outf)

        for gene_name, region_file, pb_stats_file, il_stats_file, shared_stats_file, pb_frac_map_file, il_frac_map_file in zip(gene_names, regions, pb_SNV_stats, il_SNV_stats, shared_SNV_stats, pb_frac_map, il_frac_map):

            region = parse_file(region_file)

            pb_num_SNVs = get_snp_count(pb_stats_file)
            il_num_SNVs = get_snp_count(il_stats_file)
            shared_num_SNVs = get_snp_count(shared_stats_file)

            pb_frac_map = float(parse_file(pb_frac_map_file))
            il_frac_map = float(parse_file(il_frac_map_file))

            line = '{} & {} & {} & {} & {} & {:.1f}\% & {:.1f}\% \\\\'.format(gene_name, region,
                                                  pb_num_SNVs, il_num_SNVs, shared_num_SNVs,
                                                  pb_frac_map*100, il_frac_map*100)
            print(line,file=outf)

        tail_part = '''\\hline
\\end{tabular}
\\caption{{\\bf Summary of read mappability and variants called for genes occuring
inside segmental duplications.} Data shown is for NA12878, $30\\times$ coverage
Illumina reads and $44\\times$ coverage PacBio reads. For the purposes of this
figure ``Mappable" is defined as having at least $10\\times$ coverage of
well-mapped reads (mapq $\\geq 30$).}
\\label{tab:mendelian}
\\end{table}'''

        print(tail_part,file=outf)

def make_venn_diagram_variants_outside_GIAB(longshot_vcf, giab_vcf, plat_vcf, output_png):

    def vcf2set(vcf_file):
        vcfset = set()
        with pysam.VariantFile(vcf_file) as vcf:

            for record in vcf:
                vcfset.add((record.chrom, record.pos))# tuple(record.alleles), tuple(sorted(record.samples[0]['GT']))))

        return vcfset

    plt.figure()
    venn3([vcf2set(longshot_vcf),vcf2set(giab_vcf),vcf2set(plat_vcf)],
          set_labels=['Longshot', 'GIAB', 'Platinum Genomes'])
    plt.savefig(output_png,dpi=600)


if __name__ == '__main__':
    args = parseargs()
    plot_vcfeval(args.input_dirs, args.labels, args.output_file, args.title)

def make_table_filtered_indels(median_covs,
                         NA12878_vcfeval_nofilter, NA12878_vcfeval_filter,
                         NA24385_vcfeval_nofilter, NA24385_vcfeval_filter,
                         NA24149_vcfeval_nofilter, NA24149_vcfeval_filter,
                         NA24143_vcfeval_nofilter, NA24143_vcfeval_filter,
                         gq_cutoffs, outfile):

    NA12878_nofilter_prec, NA12878_nofilter_recall = get_precision_recall(NA12878_vcfeval_nofilter, gq_cutoffs[0])
    NA12878_filter_prec, NA12878_filter_recall = get_precision_recall(NA12878_vcfeval_filter, gq_cutoffs[0])

    NA24385_nofilter_prec, NA24385_nofilter_recall = get_precision_recall(NA24385_vcfeval_nofilter, gq_cutoffs[1])
    NA24385_filter_prec, NA24385_filter_recall = get_precision_recall(NA24385_vcfeval_filter, gq_cutoffs[1])

    NA24149_nofilter_prec, NA24149_nofilter_recall = get_precision_recall(NA24149_vcfeval_nofilter, gq_cutoffs[2])
    NA24149_filter_prec, NA24149_filter_recall = get_precision_recall(NA24149_vcfeval_filter, gq_cutoffs[2])

    NA24143_nofilter_prec, NA24143_nofilter_recall = get_precision_recall(NA24143_vcfeval_nofilter, gq_cutoffs[3])
    NA24143_filter_prec, NA24143_filter_recall = get_precision_recall(NA24143_vcfeval_filter, gq_cutoffs[3])
    s = '''
\\begin{{table}}[htbp]
\\centering
\\begin{{tabular}}{{llllll}}
\\hline
Genome      & Read     & Precision      & Precision      & Recall         & Recall         \\\\
            & Coverage & (known indels  & (known indels  & (known indels  & (known indels  \\\\
            &          &  not filtered) &  filtered out) &  not filtered) &  filtered out) \\\\

\\hline
NA12878   & ${}\\times$ & ${:.3f}$ & ${:.3f}$  & ${:.3f}$ & ${:.3f}$ \\\\
NA24385 (AJ son) & ${}\\times$ & ${:.3f}$ & ${:.3f}$ & ${:.3f}$ & ${:.3f}$ \\\\
NA24149 (AJ father) & ${}\\times$ & ${:.3f}$ & ${:.3f}$ & ${:.3f}$ & ${:.3f}$ \\\\
NA24143 (AJ mother) & ${}\\times$ & ${:.3f}$ & ${:.3f}$ & ${:.3f}$ & ${:.3f}$ \\\\
# \\hline
\\end{{tabular}}
\\caption{{{{\\bf Improvement in variant precision by filtering out SNVs within 5 bp of common indel variants (Mills + 1000g Indel variant set from the GATK bundle.}}}}
\\label{{tab:stats}}
\\end{{table}}
'''.format(median_covs[0], NA12878_nofilter_prec, NA12878_filter_prec, NA12878_nofilter_recall, NA12878_filter_recall,
           median_covs[1], NA24385_nofilter_prec, NA24385_filter_prec, NA24385_nofilter_recall, NA24385_filter_recall,
           median_covs[2], NA24149_nofilter_prec, NA24149_filter_prec, NA24149_nofilter_recall, NA24149_filter_recall,
           median_covs[3], NA24143_nofilter_prec, NA24143_filter_prec, NA24143_nofilter_recall, NA24143_filter_recall)

    with open(outfile,'w') as outf:
        print(s, file=outf)
